version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: nestjs_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
